background {
    monitor =
    path = $HOME/Desktop/wallpapers/yoimiya/Yoimiya.full.3456712.png  # only png supported for now
    color = rgba(25, 20, 20, 1.0)

    # all these options are taken from hyprland, see https://wiki.hyprland.org/Configuring/Variables/#blur for explanations
    blur_passes = 0 # 0 disables blurring
    # blur_size = 2
    noise = 0.1
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 1
    dots_center = true
    outer_color = rgb(000000)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    hide_input = false
    halign = center
    valign = center
}
