
general {
    lock_cmd = hyprlock 
    unlock_cmd = pkill -USR1 hyprlock 
    before_sleep_cmd = loginctl lock-session
    ignore_dbus_inhibit = false
}

# Screenlock
listener {
    timeout = 300
    on-timeout = loginctl lock-session 
}

# Suspend
listener {
    timeout = 600
    on-timeout = systemctl suspend
}

