
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
# kitty transparency
windowrule = opacity 0.95 override 0.95 override,^(kitty)$ # set opacity to 1.0 active and 0.5 inactive for kitty
